version: '3.8'

services:
  app:
    build: .
    container_name: project-manager-app
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "mysql://projectmanager:Brewing4-Prankster-Strategic@23.94.84.111:3307/projectmanagerdb"
